<?php

namespace PAX\Support;

class Currencies
{
    protected static $currencies = [
        'ALL' => 'ALL',
        'AFN' => 'AFN',
        'ARN' => 'ARS',
        'AWG' => 'AWG',
        'AUD' => 'AUD',
        'AZN' => 'AZN',
        'BSD' => 'BSD',
        'BBD' => 'BBD',
        'BDT' => 'BDT',
        'BYR' => 'BYR',
        'BZD' => 'BZD',
        'BMD' => 'BMD',
        'BOB' => 'BOB',
        'BAM' => 'BAM',
        'BWP' => 'BWP',
        'BGN' => 'BGN',
        'BRL' => 'BRL',
        'BND' => 'BND',
        'KHR' => 'KHR',
        'CAD' => 'CAD',
        'CID' => 'KYD',
        'CHP' => 'CLP',
        'CNY' => 'CNY',
        'COP' => 'COP',
        'CRC' => 'CRC',
        'HRK' => 'HRK',
        'CUP' => 'CUP',
        'CZK' => 'CZK',
        'DKK' => 'DKK',
        'DOP' => 'DOP',
        'XCD' => 'XCD',
        'EGP' => 'EGP',
        'SVC' => 'SVC',
        'EEK' => 'EEK',
        'EUR' => 'EUR',
        'FKP' => 'FKP',
        'FJD' => 'FJD',
        'GHC' => 'GHC',
        'GIP' => 'GIP',
        'GTQ' => 'GTQ',
        'GGP' => 'GGP',
        'GYD' => 'GYD',
        'HNL' => 'HNL',
        'HKD' => 'HKD',
        'HUF' => 'HUF',
        'ISK' => 'ISK',
        'INR' => 'INR',
        'IDR' => 'IDR',
        'IRR' => 'IRR',
        'IMP' => 'IMP',
        'ILS' => 'ILS',
        'JMD' => 'JMD',
        'JYE' => 'JPY',
        'JEP' => 'JEP',
        'KZT' => 'KZT',
        'KPW' => 'KPW',
        'KRW' => 'KRW',
        'KGS' => 'KGS',
        'LAK' => 'LAK',
        'LVL' => 'LVL',
        'LBP' => 'LBP',
        'LRD' => 'LRD',
        'LTL' => 'LTL',
        'MKD' => 'MKD',
        'MYR' => 'MYR',
        'MUR' => 'MUR',
        'MXN' => 'MXN',
        'MNT' => 'MNT',
        'MZN' => 'MZN',
        'NAD' => 'NAD',
        'NPR' => 'NPR',
        'ANG' => 'ANG',
        'NZD' => 'NZD',
        'NIO' => 'NIO',
        'NGN' => 'NGN',
        'NOK' => 'NOK',
        'OMR' => 'OMR',
        'PKR' => 'PKR',
        'PAB' => 'PAB',
        'PYG' => 'PYG',
        'PEN' => 'PEN',
        'PHP' => 'PHP',
        'PLN' => 'PLN',
        'QAR' => 'QAR',
        'RON' => 'RON',
        'RUB' => 'RUB',
        'SHP' => 'SHP',
        'SAR' => 'SAR',
        'RSD' => 'RSD',
        'SCR' => 'SCR',
        'SID' => 'SGD',
        'SBD' => 'SBD',
        'SOS' => 'SOS',
        'ZAR' => 'ZAR',
        'LKR' => 'LKR',
        'SEK' => 'SEK',
        'SFR' => 'CHF',
        'SRD' => 'SRD',
        'SYP' => 'SYP',
        'TWD' => 'TWD',
        'THB' => 'THB',
        'TTD' => 'TTD',
        'TRY' => 'TRY',
        'TRL' => 'TRL',
        'TVD' => 'TVD',
        'UAH' => 'UAH',
        'UKL' => 'GBP',
        'USD' => 'USD',
        'UYU' => 'UYU',
        'UZS' => 'UZS',
        'VEF' => 'VEF',
        'VND' => 'VND',
        'YER' => 'YER',
        'ZWD' => 'ZWD',
        'KES' => 'KES',

        'ZMK' => 'ZMK',
        'BHD' => 'BHD'
    ];

    protected $CUR = [
        'AFA' => 'Afghani',
        'AFN' => 'Afghani',
        'ALK' => 'Albanian old lek',
        'ALL' => 'Lek',
        'DZD' => 'Algerian Dinar',
        'USD' => 'US Dollar',
        'ADF' => 'Andorran Franc',
        'ADP' => 'Andorran Peseta',
        'EUR' => 'Euro',
        'AOR' => 'Angolan Kwanza Readjustado',
        'AON' => 'Angolan New Kwanza',
        'AOA' => 'Kwanza',
        'XCD' => 'East Caribbean Dollar', 'ARA' => 'Argentine austral', 'ARS' => 'Argentine Peso', 'ARL' => 'Argentine peso ley', 'ARM' => 'Argentine peso moneda nacional', 'ARP' => 'Peso argentino', 'AMD' => 'Armenian Dram', 'AWG' => 'Aruban Guilder', 'AUD' => 'Australian Dollar', 'ATS' => 'Austrian Schilling', 'AZM' => 'Azerbaijani manat', 'AZN' => 'Azerbaijanian Manat', 'BSD' => 'Bahamian Dollar', 'BHD' => 'Bahraini Dinar', 'BDT' => 'Taka', 'BBD' => 'Barbados Dollar', 'BYR' => 'Belarussian Ruble', 'BEC' => 'Belgian Franc (convertible)', 'BEF' => 'Belgian Franc (currency union with LUF)', 'BEL' => 'Belgian Franc (financial)', 'BZD' => 'Belize Dollar', 'XOF' => 'CFA Franc BCEAO', 'BMD' => 'Bermudian Dollar', 'INR' => 'Indian Rupee', 'BTN' => 'Ngultrum', 'BOP' => 'Bolivian peso', 'BOB' => 'Boliviano', 'BOV' => 'Mvdol', 'BAM' => 'Convertible Marks', 'BWP' => 'Pula', 'NOK' => 'Norwegian Krone', 'BRC' => 'Brazilian cruzado', 'BRB' => 'Brazilian cruzeiro', 'BRL' => 'Brazilian Real', 'BND' => 'Brunei Dollar', 'BGN' => 'Bulgarian Lev', 'BGJ' => 'Bulgarian lev A/52', 'BGK' => 'Bulgarian lev A/62', 'BGL' => 'Bulgarian lev A/99', 'BIF' => 'Burundi Franc', 'KHR' => 'Riel', 'XAF' => 'CFA Franc BEAC', 'CAD' => 'Canadian Dollar', 'CVE' => 'Cape Verde Escudo', 'KYD' => 'Cayman Islands Dollar', 'CLP' => 'Chilean Peso', 'CLF' => 'Unidades de fomento', 'CNX' => "Chinese People's Bank dollar", 'CNY' => 'Yuan Renminbi', 'COP' => 'Colombian Peso', 'COU' => 'Unidad de Valor real', 'KMF' => 'Comoro Franc', 'CDF' => 'Franc Congolais', 'NZD' => 'New Zealand Dollar', 'CRC' => 'Costa Rican Colon', 'HRK' => 'Croatian Kuna', 'CUP' => 'Cuban Peso', 'CYP' => 'Cyprus Pound', 'CZK' => 'Czech Koruna', 'CSK' => 'Czechoslovak koruna', 'CSJ' => 'Czechoslovak koruna A/53', 'DKK' => 'Danish Krone', 'DJF' => 'Djibouti Franc', 'DOP' => 'Dominican Peso', 'ECS' => 'Ecuador sucre', 'EGP' => 'Egyptian Pound', 'SVC' => 'Salvadoran colón', 'EQE' => 'Equatorial Guinean ekwele', 'ERN' => 'Nakfa', 'EEK' => 'Kroon', 'ETB' => 'Ethiopian Birr', 'FKP' => 'Falkland Island Pound', 'FJD' => 'Fiji Dollar', 'FIM' => 'Finnish Markka', 'FRF' => 'French Franc', 'XFO' => 'Gold-Franc', 'XPF' => 'CFP Franc', 'GMD' => 'Dalasi', 'GEL' => 'Lari', 'DDM' => 'East German Mark of the GDR (East Germany)', 'DEM' => 'Deutsche Mark', 'GHS' => 'Ghana Cedi', 'GHC' => 'Ghanaian cedi', 'GIP' => 'Gibraltar Pound', 'GRD' => 'Greek Drachma', 'GTQ' => 'Quetzal', 'GNF' => 'Guinea Franc', 'GNE' => 'Guinean syli', 'GWP' => 'Guinea-Bissau Peso', 'GYD' => 'Guyana Dollar', 'HTG' => 'Gourde', 'HNL' => 'Lempira', 'HKD' => 'Hong Kong Dollar', 'HUF' => 'Forint', 'ISK' => 'Iceland Krona', 'ISJ' => 'Icelandic old krona', 'IDR' => 'Rupiah', 'IRR' => 'Iranian Rial', 'IQD' => 'Iraqi Dinar', 'IEP' => 'Irish Pound (Punt in Irish language)', 'ILP' => 'Israeli lira', 'ILR' => 'Israeli old sheqel', 'ILS' => 'New Israeli Sheqel', 'ITL' => 'Italian Lira', 'JMD' => 'Jamaican Dollar', 'JPY' => 'Yen', 'JOD' => 'Jordanian Dinar', 'KZT' => 'Tenge', 'KES' => 'Kenyan Shilling', 'KPW' => 'North Korean Won', 'KRW' => 'Won', 'KWD' => 'Kuwaiti Dinar', 'KGS' => 'Som', 'LAK' => 'Kip', 'LAJ' => 'Lao kip', 'LVL' => 'Latvian Lats', 'LBP' => 'Lebanese Pound', 'LSL' => 'Loti', 'ZAR' => 'Rand', 'LRD' => 'Liberian Dollar', 'LYD' => 'Libyan Dinar', 'CHF' => 'Swiss Franc', 'LTL' => 'Lithuanian Litas', 'LUF' => 'Luxembourg Franc (currency union with BEF)', 'MOP' => 'Pataca', 'MKD' => 'Denar', 'MKN' => 'Former Yugoslav Republic of Macedonia denar A/93', 'MGA' => 'Malagasy Ariary', 'MGF' => 'Malagasy franc', 'MWK' => 'Kwacha', 'MYR' => 'Malaysian Ringgit', 'MVQ' => 'Maldive rupee', 'MVR' => 'Rufiyaa', 'MAF' => 'Mali franc', 'MTL' => 'Maltese Lira', 'MRO' => 'Ouguiya', 'MUR' => 'Mauritius Rupee', 'MXN' => 'Mexican Peso', 'MXP' => 'Mexican peso', 'MXV' => 'Mexican Unidad de Inversion (UDI)', 'MDL' => 'Moldovan Leu', 'MCF' => 'Monegasque franc (currency union with FRF)', 'MNT' => 'Tugrik', 'MAD' => 'Moroccan Dirham', 'MZN' => 'Metical', 'MZM' => 'Mozambican metical', 'MMK' => 'Kyat', 'NAD' => 'Namibia Dollar', 'NPR' => 'Nepalese Rupee', 'NLG' => 'Netherlands Guilder', 'ANG' => 'Netherlands Antillian Guilder', 'NIO' => 'Cordoba Oro', 'NGN' => 'Naira', 'OMR' => 'Rial Omani', 'PKR' => 'Pakistan Rupee', 'PAB' => 'Balboa', 'PGK' => 'Kina', 'PYG' => 'Guarani', 'YDD' => 'South Yemeni dinar', 'PEN' => 'Nuevo Sol', 'PEI' => 'Peruvian inti', 'PEH' => 'Peruvian sol', 'PHP' => 'Philippine Peso', 'PLZ' => 'Polish zloty A/94', 'PLN' => 'Zloty', 'PTE' => 'Portuguese Escudo', 'TPE' => 'Portuguese Timorese escudo', 'QAR' => 'Qatari Rial', 'RON' => 'New Leu', 'ROL' => 'Romanian leu A/05', 'ROK' => 'Romanian leu A/52', 'RUB' => 'Russian Ruble', 'RWF' => 'Rwanda Franc', 'SHP' => 'Saint Helena Pound', 'WST' => 'Tala', 'STD' => 'Dobra', 'SAR' => 'Saudi Riyal', 'RSD' => 'Serbian Dinar', 'CSD' => 'Serbian Dinar', 'SCR' => 'Seychelles Rupee', 'SLL' => 'Leone', 'SGD' => 'Singapore Dollar', 'SKK' => 'Slovak Koruna', 'SIT' => 'Slovenian Tolar', 'SBD' => 'Solomon Islands Dollar', 'SOS' => 'Somali Shilling', 'ZAL' => 'South African financial rand (Funds code) (discont', 'ESP' => 'Spanish Peseta', 'ESA' => 'Spanish peseta (account A)', 'ESB' => 'Spanish peseta (account B)', 'LKR' => 'Sri Lanka Rupee', 'SDD' => 'Sudanese Dinar', 'SDP' => 'Sudanese Pound', 'SDG' => 'Sudanese Pound', 'SRD' => 'Surinam Dollar', 'SRG' => 'Suriname guilder', 'SZL' => 'Lilangeni', 'SEK' => 'Swedish Krona', 'CHE' => 'WIR Euro', 'CHW' => 'WIR Franc', 'SYP' => 'Syrian Pound', 'TWD' => 'New Taiwan Dollar', 'TJS' => 'Somoni', 'TJR' => 'Tajikistan ruble', 'TZS' => 'Tanzanian Shilling', 'THB' => 'Baht', 'TOP' => "Pa'anga", 'TTD' => 'Trinidata and Tobago Dollar', 'TND' => 'Tunisian Dinar', 'TRY' => 'New Turkish Lira', 'TRL' => 'Turkish lira A/05', 'TMM' => 'Manat', 'RUR' => 'Russian rubleA/97', 'SUR' => 'Soviet Union ruble', 'UGX' => 'Uganda Shilling', 'UGS' => 'Ugandan shilling A/87', 'UAH' => 'Hryvnia', 'UAK' => 'Ukrainian karbovanets', 'AED' => 'UAE Dirham', 'GBP' => 'Pound Sterling', 'USN' => 'US Dollar (Next Day)', 'USS' => 'US Dollar (Same Day)', 'UYU' => 'Peso Uruguayo', 'UYN' => 'Uruguay old peso', 'UYI' => 'Uruguay Peso en Unidades Indexadas', 'UZS' => 'Uzbekistan Sum', 'VUV' => 'Vatu', 'VEF' => 'Bolivar Fuerte', 'VEB' => 'Venezuelan Bolivar', 'VND' => 'Dong', 'VNC' => 'Vietnamese old dong', 'YER' => 'Yemeni Rial', 'YUD' => 'Yugoslav Dinar', 'YUM' => 'Yugoslav dinar (new)', 'ZRN' => 'Zairean New Zaire', 'ZRZ' => 'Zairean Zaire', 'ZMK' => 'Kwacha', 'ZWD' => 'Zimbabwe Dollar', 'ZWC' => 'Zimbabwe Rhodesian dollar'];

    public static function getBase($abstract)
    {
        if (! isset(self::$currencies[$abstract])) {
            return 'USD';
        }

        return self::$currencies[$abstract];
    }
}
